export const MOCK_PARKING_SPOTS = [
  {
    id: 1,
    address: '123 Main Street, Downtown',
    price: 5.5,
    rating: 4.8,
    reviews: 24,
    hostName: 'John Smith',
    photo: 'https://placehold.co/400x300/D3D3D3/666666?text=Driveway+Photo',
    availableTimes: ['09:00 AM', '02:00 PM', '06:00 PM'],
    description: 'Clean, well-lit driveway near downtown.',
  },
  {
    id: 2,
    address: '456 Oak Avenue, Midtown',
    price: 4.8,
    rating: 4.6,
    reviews: 18,
    hostName: 'Sarah Johnson',
    photo: 'https://placehold.co/400x300/ADD8E6/4682B4?text=Parking+Spot',
    availableTimes: ['08:00 AM', '01:00 PM', '05:00 PM'],
    description: 'Spacious parking spot with 24/7 security.',
  },
  {
    id: 3,
    address: '789 Pine Road, Suburbs',
    price: 3.5,
    rating: 4.9,
    reviews: 32,
    hostName: 'Mike Chen',
    photo: 'https://placehold.co/400x300/90EE90/228B22?text=Parking+Spot',
    availableTimes: ['07:00 AM', '12:00 PM', '04:00 PM'],
    description: 'Covered parking in quiet residential area.',
  },
  {
    id: 4,
    address: '321 Elm Street, Arts District',
    price: 6.2,
    rating: 4.7,
    reviews: 15,
    hostName: 'Emma Wilson',
    photo: 'https://placehold.co/400x300/FFE4B5/FF8C00?text=Driveway+Photo',
    availableTimes: ['10:00 AM', '03:00 PM', '08:00 PM'],
    description: 'Premium spot near restaurants and galleries.',
  },
  {
    id: 5,
    address: '654 Maple Lane, Riverside',
    price: 4.0,
    rating: 4.5,
    reviews: 22,
    hostName: 'David Brown',
    photo: 'https://placehold.co/400x300/DDA0DD/8B008B?text=Parking+Spot',
    availableTimes: ['09:30 AM', '02:30 PM', '07:00 PM'],
    description: 'Waterfront parking with scenic views.',
  },
  {
    id: 6,
    address: '987 Cedar Court, Central',
    price: 5.8,
    rating: 4.8,
    reviews: 28,
    hostName: 'Lisa Anderson',
    photo: 'https://placehold.co/400x300/F0E68C/DAA520?text=Driveway+Photo',
    availableTimes: ['08:30 AM', '01:30 PM', '06:30 PM'],
    description: 'Convenient central location near metro.',
  },
];

export const DEMO_USER = {
  id: 'user_123',
  email: 'demo@parkmate.com',
  name: 'Demo User',
  isLoggedIn: false,
};
